### ISSUE TITLE
Doesn't work well for FF in GDB mode

### ISSUE THREAD

**Issue by wmww** [wmww/wayland-debug#40]
When I run Firefox with it in GDB mode there are lots of thread warnings and I've also seen crashes related to `gtk_primary_selection_device`.

**Comment by wmww** [comment]
```
ERROR:core.wl.object:Unable to resolve object unresolved gtk_primary_selection_device@44.?: zwp_primary_selection_device_v1@44.0 expected to be of type gtk_primary_selection_device
Traceback (most recent call last):
  File "/home/wmww/code/wayland-debug/backends/gdb_plugin/plugin.py", line 72, in stop
    self.plugin.process_message(connection_id, message)
  File "/home/wmww/code/wayland-debug/backends/gdb_plugin/plugin.py", line 156, in process_message
    self.connection_id_sink.message(connection_id, message)
  File "/home/wmww/code/wayland-debug/core/connection_manager.py", line 47, in message
    connection.message(message)
  File "/home/wmww/code/wayland-debug/core/connection_impl.py", line 39, in message
    message.resolve(self)
  File "/home/wmww/code/wayland-debug/core/wl/message.py", line 38, in resolve
    arg.resolve(db, self, i)
  File "/home/wmww/code/wayland-debug/core/wl/arg.py", line 89, in resolve
    db.create_object(message.timestamp, message.obj, self.obj.id, self.obj.type)
  File "/home/wmww/code/wayland-debug/core/connection_impl.py", line 110, in create_object
    assert isinstance(parent, wl.Object)
AssertionError
```
