### ISSUE TITLE
Lots of assertions errors when trying to debug in GDB mode

### ISSUE THREAD

**Issue by morgan-dgk** [wmww/wayland-debug#59]
Hi, this tool works great when used in run mode but when I try and debug the same program in gdb mode I get a bunch of assertion errors of the form:

```
Traceback (most recent call last):
  File "/usr/lib/wayland_debug/backends/gdb_plugin/plugin.py", line 70, in stop
    connection_id, message = self.message_extractor()
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/wayland_debug/backends/gdb_plugin/extract.py", line 153, in sent_message
    object = wl.UnresolvedObject(object_id, None)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/wayland_debug/core/wl/object.py", line 85, in __init__
    super().__init__(obj_id)
  File "/usr/lib/wayland_debug/core/wl/object.py", line 12, in __init__
    assert obj_id > 0
           ^^^^^^^^^^
AssertionError
```
When I open GDB via the flag, I also see:

```
Function "wl_connection_destroy" not defined.
Function "wl_closure_invoke" not defined.
Function "wl_closure_dispatch" not defined.
Function "serialize_closure" not defined.
```

Any ideas as to what might be going on?

**Comment by wmww** [comment]
Perhaps it's using your system's libwayland, which doesn't have debug symbols? If you're using the snap I don't know what's going on, but if you're running it another way try running `./resources/get-libwayland.sh` and see if that works.
